### ISSUE TITLE
AndroidJavaException: java.lang.ClassNotFoundException: com.cartoontexas.andyr.unityplugin.ContentOpener

### ISSUE THREAD

**Issue by aadi3124** [Andy-Roger/UnityAndroidNativeFileOpener#3]
AndroidJavaException: java.lang.ClassNotFoundException: com.cartoontexas.andyr.unityplugin.ContentOpener
01-15 14:08:15.502 22334 22456 E Unity   : java.lang.ClassNotFoundException: com.cartoontexas.andyr.unityplugin.ContentOpener
01-15 14:08:15.502 22334 22456 E Unity   :      at java.lang.Class.classForName(Native Method)
01-15 14:08:15.502 22334 22456 E Unity   :      at java.lang.Class.forName(Class.java:453)
01-15 14:08:15.502 22334 22456 E Unity   :      at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
01-15 14:08:15.502 22334 22456 E Unity   :      at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
01-15 14:08:15.502 22334 22456 E Unity   :      at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
01-15 14:08:15.502 22334 22456 E Unity   :      at android.os.Handler.dispatchMessage(Handler.java:102)
01-15 14:08:15.502 22334 22456 E Unity   :      at android.os.Looper.loop(Looper.java:201)
01-15 14:08:15.502 22334 22456 E Unity   :      at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
01-15 14:08:15.502 22334 22456 E Unity   : Caused by: java.lang.ClassNotFoundException: Didn't find class "com.cartoontexas.andyr.unityplugin.ContentOpener" on path: DexPathList[[zip file "/data/app/com.litifer.android.myhoggy-tNHDWzR8jwFfzWsx_qvF0g==/base.apk"],nativeLibraryDirectories=[/data/app/com.litifer.android.myhoggy-tNHDWzR8jwFfzWsx_qvF0g==/lib/arm, /data/app/com.litifer.android.myhoggy-tNHDWzR8jwFfzWsx_qvF0g==/ba

**Comment by aadi3124** [comment]
I have added a manifest file inside plugins/Android/AndroidManifest.xml

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
          package="com.unity3d.player"
          xmlns:tools="http://schemas.android.com/tools" >

  <application>
    <provider
      android:name="com.cartoontexas.andyr.unityplugin.UnitySSContentProvider"
      android:authorities="com.litifer.android.myhoggy"
      android:exported="false"
      android:grantUriPermissions="true" />
    <provider/>
  </application>

</manifest>


After adding this I am getting the build error and not able to make build 
	Missing 'name' key attribute on element provider at AndroidManifest.xml:5:5-17

Please suggest me a solution. 
Thanks!
